spring:
  profiles:
    # si no se especifica, arranca en dev
    default: dev

# --- DEV (H2) ---------------------------------------------------------------
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate     # Flyway maneja el schema; validate por seguridad
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# --- PROD (PostgreSQL) ------------------------------------------------------
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    # por si querés customizar:
    # schemas: public
    # create-schemas: true
